// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Answers struct {
	First  string `json:"first"`
	Second string `json:"second"`
	Third  string `json:"third"`
	Fourth string `json:"fourth"`
}

type InputAnswers struct {
	First  string `json:"first"`
	Second string `json:"second"`
	Third  string `json:"third"`
	Fourth string `json:"fourth"`
}

type NewQuestion struct {
	Name    string          `json:"name"`
	TestID  string          `json:"testID"`
	Text    string          `json:"text"`
	ImgURL  *string         `json:"imgURL"`
	Answers []*InputAnswers `json:"answers"`
}

type NewTest struct {
	Name string `json:"name"`
}

type Question struct {
	ID          string   `json:"id"`
	TestID      string   `json:"testID"`
	Text        string   `json:"text"`
	ImgURL      *string  `json:"imgURL"`
	Answers     *Answers `json:"answers"`
	RightAnswer string   `json:"rightAnswer"`
}

type Test struct {
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	Questions []*Question `json:"questions"`
}
